
from typing import Optional

from pydantic import BaseModel


# ============================================================
# FUNCTION URLS
# ============================================================

class ReportingFunctionUrls(BaseModel):
    """
    Dynamically resolved Azure Function URLs required
    by Reporting 02, Reporting 03, Reporting 04 and
    Reporting 1.5.
    """

    # --------------------------------------------------------
    # Reporting 04
    # --------------------------------------------------------

    split_vulnerabilities_function_url: str

    # --------------------------------------------------------
    # Reporting 03
    # --------------------------------------------------------

    after_scoping_triaging_url: Optional[str] = None
    triaging_validator_url: Optional[str] = None

    # --------------------------------------------------------
    # Reporting 02
    # --------------------------------------------------------

    data_merging_function_url: Optional[str] = None
    new_vulnerabilities_function_url: Optional[str] = None
    servicenow_api_url: Optional[str] = None
    config_service_url: Optional[str] = None

    # --------------------------------------------------------
    # Reporting 1.5
    # --------------------------------------------------------

    check_qualys_report_url: Optional[str] = None
    download_qualys_report_url: Optional[str] = None
    get_dfn_report_url: Optional[str] = None


# ============================================================
# LOGIC APP URLS
# ============================================================

class ReportingLogicAppUrls(BaseModel):
    """
    Dynamically resolved Logic App callback URLs.
    """

    # --------------------------------------------------------
    # Notification Logic App
    # --------------------------------------------------------

    notification_service_url: str

    # --------------------------------------------------------
    # Existing Completion Logic App
    #
    # DO NOT CHANGE EXISTING FLOW
    # --------------------------------------------------------

    completion_url: Optional[str] = None
    completion_sas_token: Optional[str] = None

    # --------------------------------------------------------
    # Reporting 02 Completion Notification Logic App
    # --------------------------------------------------------

    completion_notification_logic_app_url: Optional[str] = None

    # --------------------------------------------------------
    # Reporting 1.5 callback
    #
    # This is obtained dynamically from Reporting 02.
    # It is NOT supplied by the user.
    # --------------------------------------------------------

    callback_uri_1_5: Optional[str] = None


# ============================================================
# DEPLOYMENT REQUEST
# ============================================================

class ReportingDeploymentRequest(BaseModel):
    """
    Request model for Reporting deployment.

    Existing deployment flow:

        Reporting 04
            ↓
        Reporting 03
            ↓
        Reporting 03 callback URL
            ↓
        Reporting 02

    New Reporting 1.5 flow:

        Reporting 02
            ↓
        Reporting 02 callback URL
            ↓
        Reporting 1.5

    Reporting 1.5 dynamically resolves:

        - Check Qualys Report Function URL
        - Download Qualys Report Function URL
        - Get DFN Report Function URL

    The user provides Function App name + Function name
    for each of the above functions.

    callbackUri1.5 is generated by the backend from
    the Reporting 02 HTTP trigger callback URL.
    """

    # ========================================================
    # Azure infrastructure
    # ========================================================

    subscription_id: str
    resource_group_name: str
    location: str

    # ========================================================
    # Reporting Logic Apps
    # ========================================================

    # --------------------------------------------------------
    # Reporting 04
    # --------------------------------------------------------

    reporting_logic_app_name: str = "LA-reporting-04"

    # --------------------------------------------------------
    # Reporting 03
    # --------------------------------------------------------

    reporting_03_logic_app_name: str = "LA-reporting-03"

    # --------------------------------------------------------
    # Reporting 02
    # --------------------------------------------------------

    reporting_02_logic_app_name: str = "LA-Reporting02"

    # --------------------------------------------------------
    # Reporting 1.5
    # --------------------------------------------------------

    reporting_1_5_logic_app_name: str = "LA-reporting-1.5"

    # ========================================================
    # Storage Account
    # ========================================================

    storage_account_name: str

    # ========================================================
    # SharePoint
    # ========================================================

    share_point_site_url: str

    # ========================================================
    # Notification Logic App
    # ========================================================

    notification_logic_app_name: str
    notification_logic_app_trigger_name: str

    # ========================================================
    # Existing Completion Logic App
    #
    # DO NOT CHANGE EXISTING FLOW
    # ========================================================

    completion_logic_app_name: str
    completion_logic_app_trigger_name: str

    # ========================================================
    # Separate Completion Notification Logic App
    #
    # Used by Reporting 02.
    # ========================================================

    completion_notification_logic_app_name: str
    completion_notification_logic_app_trigger_name: str

    # ========================================================
    # Reporting 04 - Split Vulnerabilities Function
    # ========================================================

    function_app_name: str
    split_vulnerabilities_function_name: str

    # ========================================================
    # Reporting 03 - After Scoping Triaging Function
    # ========================================================

    after_scoping_triaging_function_app_name: Optional[str] = None
    after_scoping_triaging_function_name: Optional[str] = None

    # ========================================================
    # Reporting 03 - Triaging Validator Function
    # ========================================================

    triaging_validator_function_app_name: Optional[str] = None
    triaging_validator_function_name: Optional[str] = None

    # ========================================================
    # Reporting 02 - Data Merging Function
    # ========================================================

    data_merging_function_app_name: str
    data_merging_function_name: str

    # ========================================================
    # Reporting 02 - New Vulnerabilities Function
    # ========================================================

    new_vulnerabilities_function_app_name: str
    new_vulnerabilities_function_name: str

    # ========================================================
    # Reporting 02 - ServiceNow Function
    # ========================================================

    servicenow_function_app_name: str
    servicenow_function_name: str

    # ========================================================
    # Reporting 02 - Config Service Function
    # ========================================================

    config_service_function_app_name: str
    config_service_function_name: str

    # ========================================================
    # Reporting 1.5 - Check Qualys Report Function
    #
    # User provides:
    #     Function App Name
    #     Function Name
    #
    # Backend dynamically gets:
    #     checkQualysReportUrl
    # ========================================================

    check_qualys_report_function_app_name: str
    check_qualys_report_function_name: str

    # ========================================================
    # Reporting 1.5 - Download Qualys Report Function
    #
    # User provides:
    #     Function App Name
    #     Function Name
    #
    # Backend dynamically gets:
    #     downloadQualysReportUrl
    # ========================================================

    download_qualys_report_function_app_name: str
    download_qualys_report_function_name: str

    # ========================================================
    # Reporting 1.5 - Get DFN Report Function
    #
    # User provides:
    #     Function App Name
    #     Function Name
    #
    # Backend dynamically gets:
    #     getDfnReportUrl
    # ========================================================

    get_dfn_report_function_app_name: str
    get_dfn_report_function_name: str

    # ========================================================
    # Callback Secret
    # ========================================================

    # Existing callback secret used by Reporting 03.
    callback_secret_key: str

    # ========================================================
    # Azure API Connections
    # ========================================================

    azure_tables_connection_name: str = "azuretables-1"

    sharepoint_connection_name: str = "sharepointonline-1"

    azure_queue_connection_name: str = "azurequeues-1"


# ============================================================
# DEPLOYMENT RESPONSE
# ============================================================

class ReportingDeploymentResponse(BaseModel):
    """
    Response returned after Reporting deployment.

    Deployment flow:

        Reporting 04
            ↓
        Reporting 03
            ↓
        Reporting 02
            ↓
        Reporting 1.5

    Dynamic callback URLs and Function URLs are returned
    in the response.
    """

    success: bool
    message: str

    # ========================================================
    # Azure infrastructure
    # ========================================================

    subscription_id: str
    resource_group_name: str
    location: str

    # ========================================================
    # Reporting Logic Apps
    # ========================================================

    reporting_logic_app_name: str

    reporting_03_logic_app_name: Optional[str] = None

    reporting_02_logic_app_name: Optional[str] = None

    reporting_1_5_logic_app_name: Optional[str] = None

    # ========================================================
    # Storage
    # ========================================================

    storage_account_name: str

    # ========================================================
    # Reporting 04 deployment
    # ========================================================

    deployment_name: Optional[str] = None
    provisioning_state: Optional[str] = None

    # ========================================================
    # Reporting 03 deployment
    # ========================================================

    reporting_03_deployment_name: Optional[str] = None
    reporting_03_provisioning_state: Optional[str] = None

    # ========================================================
    # Reporting 02 deployment
    # ========================================================

    reporting_02_deployment_name: Optional[str] = None
    reporting_02_provisioning_state: Optional[str] = None

    # ========================================================
    # Reporting 1.5 deployment
    # ========================================================

    reporting_1_5_deployment_name: Optional[str] = None
    reporting_1_5_provisioning_state: Optional[str] = None

    # ========================================================
    # API connection IDs
    # ========================================================

    table_connection_id: Optional[str] = None
    sharepoint_connection_id: Optional[str] = None
    queue_connection_id: Optional[str] = None

    # ========================================================
    # Reporting 04 callback URL
    #
    # Existing flow.
    #
    # Passed to Reporting 03 as callbackUrl.
    # ========================================================

    callback_url: Optional[str] = None

    # ========================================================
    # Reporting 03 callback URL
    #
    # Passed to Reporting 02 as callbackUri02.
    # ========================================================

    reporting_03_callback_url: Optional[str] = None

    # ========================================================
    # Reporting 02 callback URL
    #
    # Used to create callbackUri1.5.
    # ========================================================

    reporting_02_callback_url: Optional[str] = None

    # ========================================================
    # Dynamically resolved Function URLs
    # ========================================================

    function_urls: Optional[ReportingFunctionUrls] = None

    # ========================================================
    # Dynamically resolved Logic App URLs
    # ========================================================

    logic_app_urls: Optional[ReportingLogicAppUrls] = None

    # ========================================================
    # Existing Completion callback values
    #
    # DO NOT CHANGE EXISTING FLOW
    # ========================================================

    completion_url: Optional[str] = None
    completion_sas_token: Optional[str] = None

    # ========================================================
    # Reporting 02 Completion Notification URL
    # ========================================================

    completion_notification_logic_app_url: Optional[str] = None

    # ========================================================
    # Reporting 1.5 callback URL
    #
    # Final dynamically resolved value.
    # ========================================================

    callback_uri_1_5: Optional[str] = None
