
from typing import Optional

from pydantic import BaseModel, Field


# ============================================================
# SCOPING DEPLOYMENT REQUEST
# ============================================================

class ScopingDeploymentRequest(BaseModel):
    """
    Request model for deploying:

        LA-Scoping-00
        LA-Scoping-01

    using arm/scoping.json.

    CMDBReportURL is NOT supplied by the frontend.
    It is generated by Scoping-01 during workflow execution.
    """

    # ========================================================
    # AZURE
    # ========================================================

    subscription_id: str = Field(
        ...,
        min_length=1,
    )

    resource_group_name: str = Field(
        ...,
        min_length=1,
    )

    location: str = Field(
        ...,
        min_length=1,
    )

    # ========================================================
    # LOGIC APPS
    # ========================================================

    logic_app_name: str = Field(
        default="LA-Scoping-00",
    )

    scoping01_logic_app_name: str = Field(
        default="LA-Scoping-01",
    )

    # ========================================================
    # STORAGE / QUEUE / TABLE
    # ========================================================

    storage_account_name: str = Field(
        ...,
        min_length=1,
    )

    scoping_schedule_queue_name: str = Field(
        ...,
        min_length=1,
    )

    notification_log_table_name: str = Field(
        ...,
        min_length=1,
    )

    # ========================================================
    # SHAREPOINT
    # ========================================================

    share_point_url: str = Field(
        ...,
        min_length=1,
    )

    sharepoint_connection_name: str = Field(
        default="sharepointonline-1",
    )

    # ========================================================
    # CALLBACK
    # ========================================================

    completion_logic_app_url: str = Field(
        ...,
        min_length=1,
    )

    callback_secret_key: str = Field(
        ...,
        min_length=1,
    )

    # ========================================================
    # NOTIFICATION
    # ========================================================

    notification_service_url: str = Field(
        ...,
        min_length=1,
    )

    notification_status: str = Field(
        ...,
        min_length=1,
    )

    # ========================================================
    # FUNCTION APP
    # ========================================================

    function_app_name: str = Field(
        ...,
        min_length=1,
    )

    # ========================================================
    # FUNCTION NAMES
    # ========================================================

    config_function_name: str = Field(
        default="GetPartitionConfigs",
    )

    business_day_hour_status_function_name: str = Field(
        default="IsBusinessDayAndHour",
    )

    get_next_business_day_function_name: str = Field(
        default="GetNextBusinessDay",
    )

    call_azure_function_name: str = Field(
        default="ProcessAzureIPData",
    )

    # ========================================================
    # API CONNECTIONS
    # ========================================================

    table_connection_name: str = Field(
        default="azuretables-1",
    )

    queue_connection_name: str = Field(
        default="azurequeues-1",
    )


# ============================================================
# FUNCTION URL INFORMATION
# ============================================================

class ScopingFunctionUrls(BaseModel):
    """
    Function URLs resolved dynamically by the backend.

    These URLs are NOT supplied by the frontend.
    """

    config_service_url: Optional[str] = None

    business_day_hour_status_url: Optional[str] = None

    get_next_business_day_url: Optional[str] = None

    call_azure_function_url: Optional[str] = None


# ============================================================
# DEPLOYMENT RESPONSE
# ============================================================

class ScopingDeploymentResponse(BaseModel):
    """
    Response returned after Scoping-00 and Scoping-01
    Logic App deployment.
    """

    success: bool

    message: str

    # ========================================================
    # AZURE
    # ========================================================

    subscription_id: str

    resource_group_name: str

    location: str

    # ========================================================
    # LOGIC APPS
    # ========================================================

    logic_app_name: str

    scoping01_logic_app_name: str

    # ========================================================
    # STORAGE
    # ========================================================

    storage_account_name: str

    # ========================================================
    # DEPLOYMENT
    # ========================================================

    deployment_name: Optional[str] = None

    provisioning_state: Optional[str] = None

    # ========================================================
    # API CONNECTIONS
    # ========================================================

    table_connection_id: Optional[str] = None

    queue_connection_id: Optional[str] = None

    sharepoint_connection_id: Optional[str] = None

    # ========================================================
    # FUNCTION URLS
    # ========================================================

    function_urls: Optional[ScopingFunctionUrls] = None
